## DO NOT try any value which not listed below.

## Priorities
# Idle          = 64
# Below Normal  = 16384
# Normal        = 32
# Above Normal  = 32768
# High          = 128
# Realtime      = 256   (Run as Administrator is required) (Not Recommended)

## Check Microsoft official document for the details
# https://docs.microsoft.com/en-us/windows/win32/api/processthreadsapi/nf-processthreadsapi-setpriorityclass#parameters

[PriorityMod]
priority=128