## DO NOT try any value which not listed below.

## Priorities
# Idle          = 0
# Below Normal  = 1
# Normal        = 2
# Above Normal  = 3
# High          = 4
# Realtime      = 5     (Run as Administrator is required) (Not Recommended)

## Check Microsoft official document for the details
# https://docs.microsoft.com/en-us/windows/win32/api/processthreadsapi/nf-processthreadsapi-setpriorityclass#parameters

[PriorityMod]
priority=4